{ lib, pkgs, ... }: {
  # The rtk Bash hook itself is installed system-wide in
  # modules/features/claude.nix; this only adds the user-facing half of
  # `rtk init`: ~/.claude/RTK.md, which documents the few meta-commands the
  # hook cannot rewrite (`rtk gain`, `rtk discover`), plus the `@RTK.md` line
  # in ~/.claude/CLAUDE.md that pulls it into context.
  #
  # Generated by rtk rather than hand-copied so it tracks the installed
  # version. --no-patch keeps rtk away from ~/.claude/settings.json, which
  # Claude Code owns and rewrites at runtime — the hook lives in the system
  # policy file instead. Both writes are idempotent, and the CLAUDE.md
  # reference is appended without touching anything already in the file.
  home.activation.rtkInstructions = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    $DRY_RUN_CMD ${lib.getExe pkgs.rtk} init -g --no-patch > /dev/null
  '';
}
